In [ ]:
#importing modules
import numpy as np
import pandas as pd

#loading datasets
data = pd.read_csv('cervical_cancer2.csv')


In [ ]:
#the fist 5 rows
data.head(5)

Age  Number of sexual partners  First sexual intercourse  \
0   18                          4                        15   
1   15                          1                        14   
2   34                          1                         0   
3   52                          5                        16   
4   46                          3                        21   

   Num of pregnancies  Smokes  Smokes (years)  Smokes (packs/year)  \
0                   1       0             0.0                  0.0   
1                   1       0             0.0                  0.0   
2                   1       0             0.0                  0.0   
3                   4       1            37.0                 37.0   
4                   4       0             0.0                  0.0   

   Hormonal Contraceptives  Hormonal Contraceptives (years)  IUD  ...  \
0                        0                              0.0    0  ...   
1                        0                              0.0    0  ...   
2                        0                              0.0    0  ...   
3                        1                              3.0    0  ...   
4                        1                             15.0    0  ...   

   STDs: Time since first diagnosis  STDs: Time since last diagnosis  \
0                                 0                                0   
1                                 0                                0   
2                                 0                                0   
3                                 0                                0   
4                                 0                                0   

   Dx:Cancer  Dx:CIN  Dx:HPV  Dx  Hinselmann  Schiller  Citology  Biopsy  
0          0       0       0   0           0         0         0       0  
1          0       0       0   0           0         0         0       0  
2          0       0       0   0           0         0         0       0  
3          1       0       1   0           0         0         0       0  
4          0       0       0   0           0         0         0       0  

[5 rows x 36 columns]

In [ ]:
#the result
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 858 entries, 0 to 857
Data columns (total 36 columns):
Age                                   858 non-null int64
Number of sexual partners             858 non-null int64
First sexual intercourse              858 non-null int64
Num of pregnancies                    858 non-null int64
Smokes                                858 non-null int64
Smokes (years)                        858 non-null float64
Smokes (packs/year)                   858 non-null float64
Hormonal Contraceptives               858 non-null int64
Hormonal Contraceptives (years)       858 non-null float64
IUD                                   858 non-null int64
IUD (years)                           858 non-null float64
STDs                                  858 non-null int64
STDs (number)                         858 non-null int64
STDs:condylomatosis                   858 non-null int64
STDs:cervical condylomatosis          858 non-null int64
STDs:vaginal condylomatosis     

In [ ]:
#counting the diagnosis variable
data.Biopsy.value_counts()

0    803
1     55
Name: Biopsy, dtype: int64

In [ ]:
#finished the dataset preprocessing
#splitting dataset into training one and testing one
from sklearn.model_selection import train_test_split
train, test = train_test_split(data, test_size = 0.3,random_state=1234)

In [ ]:
#finished the dataset preprocessing
#splitting dataset into training one and testing one
from sklearn.model_selection import train_test_split
train, test = train_test_split(data, test_size = 0.3,random_state=1234)

#finding out the results
print(train.shape)
print(test.shape)


(600, 36)
(258, 36)


In [ ]:
#making independent variables for training
X_train = train.iloc[:, 1:36]
#making responsible variables for training
y_train=train.Biopsy
#making independent variables for testing
X_test= test.iloc[:, 1:36]
#making responsible variables for testing
y_test =test.Biopsy


In [ ]:
#finding out the results
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)


(600, 35)
(600,)
(258, 35)
(258,)


In [ ]:
#With Hyper Parameters Tuning
#2-1,DesicionTree
#importing modules
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier
#making the instance
model= DecisionTreeClassifier(random_state=1234)
#Hyper Parameters Set
params = {'criterion': ['gini','entropy'],'splitter': ['best', 'random'],'max_features': ['auto', 'sqrt', 'log2'],
          'min_samples_split': [2,3,4,5,6,7,8,9,10,11,12,13,14,15],
          'min_samples_leaf':[1,2,3,4,5,6,7,8,9,10,11],
          'random_state':[123]}
#Making models with hyper parameters sets
model1 = GridSearchCV(model, param_grid=params, n_jobs=-1)
#Learning
model1.fit(X_train,y_train)
#The best hyper parameters set
print("Best Hyper Parameters:",model1.best_params_)
#Prediction
prediction=model1.predict(X_test)
#importing the metrics module
from sklearn import metrics
#evaluation(Accuracy)
print("Accuracy:",metrics.accuracy_score(prediction,y_test))
#evaluation(Confusion Metrix)
print("Confusion Metrix:\n",metrics.confusion_matrix(prediction,y_test))
from sklearn.metrics import classification_report
print(classification_report(y_test, prediction))

/home/rachel/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)


Best Hyper Parameters: {'criterion': 'entropy', 'max_features': 'auto', 'min_samples_leaf': 1, 'min_samples_split': 8, 'random_state': 123, 'splitter': 'best'}
Accuracy: 0.9883720930232558
Confusion Metrix:
 [[236   0]
 [  3  19]]
              precision    recall  f1-score   support

           0       1.00      0.99      0.99       239
           1       0.86      1.00      0.93        19

   micro avg       0.99      0.99      0.99       258
   macro avg       0.93      0.99      0.96       258
weighted avg       0.99      0.99      0.99       258



In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate

decision_tree = DecisionTreeClassifier()

scoring = ['accuracy', 'precision_macro', 'recall_macro' , 'f1_weighted', 'roc_auc']
scores = cross_validate(decision_tree, X_train, y_train, scoring=scoring, cv=20)

sorted(scores.keys())
dtree_fit_time = scores['fit_time'].mean()
dtree_score_time = scores['score_time'].mean()
dtree_accuracy = scores['test_accuracy'].mean()
dtree_precision = scores['test_precision_macro'].mean()
dtree_recall = scores['test_recall_macro'].mean()
dtree_f1 = scores['test_f1_weighted'].mean()
dtree_roc = scores['test_roc_auc'].mean()

In [ ]:
#With Hyper Parameters Tuning
#2-2,Randomforest
#importing modules
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
#making the instance
model=RandomForestClassifier()
#hyper parameters set
params = {'criterion':['gini','entropy'],
          'n_estimators':[10,15,20,25,30],
          'min_samples_leaf':[1,2,3],
          'min_samples_split':[3,4,5,6,7],
          'random_state':[123],
          'n_jobs':[-1]}
#Making models with hyper parameters sets
model1 = GridSearchCV(model, param_grid=params, n_jobs=-1)
#learning
model1.fit(X_train,y_train)
#The best hyper parameters set
print("Best Hyper Parameters:\n",model1.best_params_)
#Prediction
prediction=model1.predict(X_test)
#importing the metrics module
from sklearn import metrics
#evaluation(Accuracy)
print("Accuracy:",metrics.accuracy_score(prediction,y_test))
#evaluation(Confusion Metrix)
print("Confusion Metrix:\n",metrics.confusion_matrix(prediction,y_test))
from sklearn.metrics import classification_report
print(classification_report(y_test, prediction))

/home/rachel/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)


Best Hyper Parameters:
 {'criterion': 'entropy', 'min_samples_leaf': 1, 'min_samples_split': 7, 'n_estimators': 10, 'n_jobs': -1, 'random_state': 123}
Accuracy: 1.0
Confusion Metrix:
 [[239   0]
 [  0  19]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       239
           1       1.00      1.00      1.00        19

   micro avg       1.00      1.00      1.00       258
   macro avg       1.00      1.00      1.00       258
weighted avg       1.00      1.00      1.00       258



In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate
random_forest = RandomForestClassifier()
scoring = ['accuracy', 'precision_macro', 'recall_macro' , 'f1_weighted', 'roc_auc']
scores = cross_validate(random_forest, X_train, y_train, scoring=scoring, cv=20)

sorted(scores.keys())
forest_fit_time = scores['fit_time'].mean()
forest_score_time = scores['score_time'].mean()
forest_accuracy = scores['test_accuracy'].mean()
forest_precision = scores['test_precision_macro'].mean()
forest_recall = scores['test_recall_macro'].mean()
forest_f1 = scores['test_f1_weighted'].mean()
forest_roc = scores['test_roc_auc'].mean()

/home/rachel/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/rachel/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/rachel/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/rachel/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/home/rachel/anaconda3/lib/python3.7/site-pa

In [ ]:
#Importing modules
import numpy as np
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.decomposition import PCA
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVC
from sklearn.ensemble import AdaBoostClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import precision_score, recall_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import warnings
warnings.filterwarnings('ignore')
import os

In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate
SVM_CV = SVC(probability = True)

scoring = ['accuracy','precision_macro', 'recall_macro' , 'f1_weighted', 'roc_auc']
scores = cross_validate(SVM_CV, X_train, y_train, scoring=scoring, cv=20)

sorted(scores.keys())
SVM_CV_fit_time = scores['fit_time'].mean()
SVM_CV_score_time = scores['score_time'].mean()
SVM_CV_accuracy = scores['test_accuracy'].mean()
SVM_CV_precision = scores['test_precision_macro'].mean()
SVM_CV_recall = scores['test_recall_macro'].mean()
SVM_CV_f1 = scores['test_f1_weighted'].mean()
SVM_CV_roc = scores['test_roc_auc'].mean()

In [ ]:
#With Hyper Parameters Tuning
#2-3,SVM
#importing modules
from sklearn.model_selection import GridSearchCV
from sklearn import svm
#making the instance
model=SVC()
#Hyper Parameters Set
params = {'C': [6,7,8,9,10,11,12],
          'kernel': ['linear','rbf']}

#Making models with hyper parameters sets
model1 = GridSearchCV(model, param_grid=params, n_jobs=-1)
#Learning
model1.fit(X_train,y_train)
#The best hyper parameters set
print("Best Hyper Parameters:\n",model1.best_params_)
#Prediction
prediction=model1.predict(X_test)
#importing the metrics module
from sklearn import metrics
#evaluation(Accuracy)
print("Accuracy:",metrics.accuracy_score(prediction,y_test))
#evaluation(Confusion Metrix)
print("Confusion Metrix:\n",metrics.confusion_matrix(prediction,y_test))
from sklearn.metrics import classification_report
print(classification_report(y_test, prediction))

Best Hyper Parameters:
 {'C': 6, 'kernel': 'linear'}
Accuracy: 1.0
Confusion Metrix:
 [[239   0]
 [  0  19]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       239
           1       1.00      1.00      1.00        19

   micro avg       1.00      1.00      1.00       258
   macro avg       1.00      1.00      1.00       258
weighted avg       1.00      1.00      1.00       258



In [ ]:
KNN_CV = KNeighborsClassifier()

scoring = ['accuracy', 'precision_macro', 'recall_macro' , 'f1_weighted', 'roc_auc']
scores = cross_validate(KNN_CV, X_train, y_train, scoring=scoring, cv=20)

sorted(scores.keys())
KNN_CV_fit_time = scores['fit_time'].mean()
KNN_CV_score_time = scores['score_time'].mean()
KNN_CV_accuracy = scores['test_accuracy'].mean()
KNN_CV_precision = scores['test_precision_macro'].mean()
KNN_CV_recall = scores['test_recall_macro'].mean()
KNN_CV_f1 = scores['test_f1_weighted'].mean()
KNN_CV_roc = scores['test_roc_auc'].mean()

In [ ]:
#With Hyper Parameters Tuning
#2-4,kNearestNeighbors
#importing modules
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
#making the instance
model = KNeighborsClassifier(n_jobs=-1)
#Hyper Parameters Set
params = {'n_neighbors':[5,6,7,8,9,10],
          'leaf_size':[1,2,3,5],
          'weights':['uniform', 'distance'],
          'algorithm':['auto', 'ball_tree','kd_tree','brute'],
          'n_jobs':[-1]}
#Making models with hyper parameters sets
model1 = GridSearchCV(model, param_grid=params, n_jobs=1)
#Learning
model1.fit(X_train,y_train)
#The best hyper parameters set
print("Best Hyper Parameters:\n",model1.best_params_)
#Prediction
prediction=model1.predict(X_test)
#importing the metrics module
from sklearn import metrics
#evaluation(Accuracy)
print("Accuracy:",metrics.accuracy_score(prediction,y_test))
#evaluation(Confusion Metrix)
print("Confusion Metrix:\n",metrics.confusion_matrix(prediction,y_test))
from sklearn.metrics import classification_report
print(classification_report(y_test, prediction))

Best Hyper Parameters:
 {'algorithm': 'auto', 'leaf_size': 1, 'n_jobs': -1, 'n_neighbors': 5, 'weights': 'uniform'}
Accuracy: 0.9263565891472868
Confusion Metrix:
 [[238  18]
 [  1   1]]
              precision    recall  f1-score   support

           0       0.93      1.00      0.96       239
           1       0.50      0.05      0.10        19

   micro avg       0.93      0.93      0.93       258
   macro avg       0.71      0.52      0.53       258
weighted avg       0.90      0.93      0.90       258

